language: ruby
before_install:
  - gem install rubygems-update -v '<3' && update_rubygems
gemfile:
  - gemfiles/rest-client-2.1.0.rc1.gemfile
  - gemfiles/rest-client-2.0.2.gemfile
  - gemfiles/rest-client-2.0.1.gemfile
script:
  - bundle exec rake spec
rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
  - 2.3.8
  - 2.2.10
  - 2.1.10
  - 2.0.0
